server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/youchunze/SpringcloudConfig.git
          search-paths: respo
          username:
          password:
      label: master
eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8889/eureka/